/// Generated By XFlutter Cli.
///

import 'package:flutter/material.dart';
import 'package:livedata_app/config/instance_config.dart';
import 'package:livedata_app/controllers/theme_controller.dart';

extension ThemeUtils on ThemeData {
  /// get current theme textColor
  Color? get textColor => textTheme.bodyText1?.color;

  /// if applied theme is dark theme
  bool isDark() => findInstance<ThemeController>().themeMode.value == ThemeMode.dark;
}
