/// Generated By XFlutter Cli.
///

import 'dart:async';
import 'base_repository.dart';
import 'package:dio/dio.dart';
import 'package:get_it/get_it.dart';
import 'package:lazy_evaluation/lazy_evaluation.dart';
import 'package:livedata_app/models/data_models.dart';
import 'package:livedata_app/models/responses/base_response/base_response.dart';
import 'package:livedata_app/network/user_rest_client/user_rest_client.dart';

class UserRepository extends BaseRepository {
  final _userRestClient = Lazy<UserRestClient>(() => UserRestClient(GetIt.I.get<Dio>()));
  UserRestClient get userRestClient => _userRestClient.value;

  Future<BaseResponse<User>> create(User user) async {
    return getResponse(() => userRestClient.create(user: user).onError((error, _) => catchError<User>(error)));
  }

  Future<BaseResponse<User>> update(String id, User user) async {
    return getResponse(() => userRestClient.update(id: id, user: user).onError((error, _) => catchError<User>(error)));
  }

  Future<BaseResponse<ListResponse<User>>> findAll(int page, {String? query}) async {
    return getResponse(() => userRestClient.findAll(page: page, query: query).onError((error, _) => catchError<ListResponse<User>>(error)));
  }

  Future<BaseResponse<User>> findOne(String id) async {
    return getResponse(() => userRestClient.findOne(id: id).onError((error, _) => catchError<User>(error)));
  }

  Future<BaseResponse<dynamic>> delete(String id) async {
    return getResponse(() => userRestClient.delete(id: id).onError((error, _) => catchError<dynamic>(error)));
  }
}
