/// Generated By XFlutter Cli.
///

import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:flutterx_live_data/flutterx_live_data.dart';
import 'package:livedata_app/router/app_router.dart';
import "package:livedata_app/ui/widgets/instance/instance_state.dart";
import "./viewmodels/register_viewmodel.dart";
import 'package:livedata_app/ui/widgets/loaders/live_data_loader.dart';
import 'package:livedata_app/ui/core/responsive/screen_type_layout.dart';
import 'mobile/register_mobile_screen.dart';
import 'tablet/register_tablet_screen.dart';
import 'package:livedata_app/ui/core/layouts/base_scaffold.dart';

class RegisterScreen extends StatefulWidget {
  const RegisterScreen({Key? key}) : super(key: key);

  @override
  State<RegisterScreen> createState() => _RegisterScreenState();
}

class _RegisterScreenState extends State<RegisterScreen> with InstanceState<RegisterScreen, RegisterViewModel>, StateObserver {
  @override
  void observeLiveData(lifeCycle, viewModel) {
    // register observers...
    viewModel.params.result.observe(lifeCycle, (value) {
      // login success
      if (value.id != null) {
        appRouter.replaceAll([const Home()]);
      }
    });
  }

  @override
  Widget screen(BuildContext context, viewModel) {
    return Stack(
      children: [
        BaseScaffold(
          appBar: (context, theme) => AppBar(
            title: Text("register".tr()),
            centerTitle: true,
          ),
          builder: (context, theme) {
            return const SafeArea(
              child: ScreenTypeLayout(
                mobile: RegisterMobileScreen(),
                tablet: RegisterTabletScreen(),
              ),
            );
          },
        ),
        LoadingListenerWidget(loading: viewModel.baseParams.loading),
      ],
    );
  }

  @override
  RegisterViewModel registerInstance() => RegisterViewModel();
}
