/// Generated By XFlutter Cli.
///

import 'package:flutter/material.dart';
import 'package:livedata_app/ui/core/layouts/base_scroll_view.dart';
import 'package:livedata_app/ui/resources/dimensions/dimensions.dart';
import "package:livedata_app/ui/widgets/instance/instance_builder.dart";
import "../viewmodels/login_viewmodel.dart";
import 'package:livedata_app/ui/core/layouts/theme_widget.dart';

import '../widgets/login_form.dart';

class LoginTabletScreen extends StatelessWidget {
  const LoginTabletScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return InstanceBuilder<LoginViewModel>(
      builder: (viewModel) {
        return ThemeWidget(
          builder: (context, theme) {
            return const Padding(
              padding: EdgeInsets.symmetric(horizontal: threeUnits, vertical: twoUnits),
              child: BaseScrollView(child: LoginForm()),
            );
          },
        );
      },
    );
  }
}
