/// Generated By XFlutter Cli.
///

///
/// declare and manage viewModel-liveData variables.
///
/// see: https://pub.dev/packages/flutterx_live_data
///
///

import 'package:livedata_app/models/data_models.dart';
import 'package:livedata_app/models/forms/formz_text.dart';
import 'package:livedata_app/extensions/live_data_extension.dart';
import 'package:livedata_app/models/forms/formz_email.dart';
import 'package:livedata_app/models/forms/formz_password.dart';
import 'package:livedata_app/models/forms/formz_confirm_password.dart';

class RegisterParams {
  /// Register username
  final username = const FormzText.pure().liveData;

  /// Register email
  final email = const FormzEmail.pure().liveData;

  /// Register password
  final password = const FormzPassword.pure().liveData;

  /// Register confirmPassword
  final confirmPassword = const FormzConfirmPassword.pure().liveData;

  /// Register result
  final result = const User().liveData;
}
