/// Generated By XFlutter Cli.
///
///
/// state management for UI
///
/// store and manage your liveData in [RegisterParams].
import 'package:livedata_app/controllers/authentication_controller.dart';
import 'package:livedata_app/extensions/formz_extensions.dart';
import 'package:livedata_app/extensions/nullable_extensions.dart';
import 'package:livedata_app/models/data_models.dart';
import 'package:livedata_app/repositories/auth_repository.dart';
import 'package:livedata_app/events/bus_events.dart';

import "register_params.dart";
import 'package:lazy_evaluation/lazy_evaluation.dart';
import 'package:livedata_app/viewmodels/base_viewmodel.dart';

import 'package:flutterx_live_data/flutterx_live_data.dart';
import 'package:livedata_app/models/forms/formz_text.dart';
import 'package:livedata_app/models/forms/formz_email.dart';
import 'package:livedata_app/models/forms/formz_password.dart';
import 'package:livedata_app/models/forms/formz_confirm_password.dart';

class RegisterViewModel extends BaseViewModel {
  final _params = Lazy(() => RegisterParams());
  RegisterParams get params => _params.value;

  final _authRepository = Lazy(() => AuthRepository());
  AuthRepository get authRepository => _authRepository.value;

  /// update [RegisterParams] some [FormzText] variable.
  void formzTextChanged(MutableLiveData<FormzText> attr, String value) {
    final newValue = FormzText.dirty(value);
    attr.postValue(newValue);
  }

  /// update [RegisterParams] some [FormzEmail] variable.
  void formzEmailChanged(MutableLiveData<FormzEmail> attr, String value) {
    final newValue = FormzEmail.dirty(value);
    attr.postValue(newValue);
  }

  /// update [RegisterParams] some [FormzPassword] variable.
  void formzPasswordChanged(MutableLiveData<FormzPassword> attr, String value) {
    final newValue = FormzPassword.dirty(value);
    attr.postValue(newValue);
  }

  /// update [RegisterParams] some [FormzConfirmPassword] variable.
  void formzConfirmPasswordChanged(MutableLiveData<FormzConfirmPassword> attr, String value) {
    final password = params.password.value.value;
    final newValue = FormzConfirmPassword.dirty(password: password, value: value);
    attr.postValue(newValue);
  }

  void register() {
    eventBus.fire(const SoftKeyboardEvent());
    final registerRequest = RegisterRequest(
      username: params.username.inputValue(),
      email: params.email.inputValue(),
      password: params.password.inputValue(),
    );

    callHttpRequest<LoginResponse>(
      () => authRepository.register(registerRequest),
      loading: baseParams.loading,
      callback: (result) => result?.user?.let((it) async {
        await AuthenticationController.login(result);
        params.result.postValue(it);
      }),
    );
  }
}
