/// Generated By XFlutter Cli.
///

import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:flutterx_live_data/flutterx_live_data.dart';
import 'package:livedata_app/router/app_router.dart';
import "package:livedata_app/ui/widgets/instance/instance_state.dart";
import "./viewmodels/login_viewmodel.dart";
import 'package:livedata_app/ui/widgets/loaders/live_data_loader.dart';
import 'package:livedata_app/ui/core/responsive/screen_type_layout.dart';
import 'mobile/login_mobile_screen.dart';
import 'tablet/login_tablet_screen.dart';
import 'package:livedata_app/ui/core/layouts/base_scaffold.dart';

class LoginScreen extends StatefulWidget {
  const LoginScreen({Key? key}) : super(key: key);

  @override
  State<LoginScreen> createState() => _LoginScreenState();
}

class _LoginScreenState extends State<LoginScreen> with InstanceState<LoginScreen, LoginViewModel>, StateObserver {
  @override
  void observeLiveData(lifeCycle, viewModel) {
    // register observers...
    viewModel.params.result.observe(lifeCycle, (value) {
      // login success
      if (value.id != null) {
        appRouter.replaceAll([const Home()]);
      }
    });
  }

  @override
  Widget screen(BuildContext context, viewModel) {
    return Stack(
      children: [
        BaseScaffold(
          appBar: (context, theme) => AppBar(
            title: Text("login".tr()),
            centerTitle: true,
          ),
          builder: (context, theme) {
            return const SafeArea(
              child: ScreenTypeLayout(
                mobile: LoginMobileScreen(),
                tablet: LoginTabletScreen(),
              ),
            );
          },
        ),
        LoadingListenerWidget(loading: viewModel.baseParams.loading),
      ],
    );
  }

  @override
  LoginViewModel registerInstance() => LoginViewModel();
}
