/// Generated By XFlutter Cli.
///

import 'package:livedata_app/ui/screens/home/home_screen.dart';
import 'package:livedata_app/ui/screens/register/register_screen.dart';
import 'package:livedata_app/ui/screens/login/login_screen.dart';
import 'package:livedata_app/ui/screens/initial/initial_screen.dart';
import 'package:flutter/material.dart';
import 'package:auto_route/auto_route.dart';

part 'app_router.gr.dart';

@MaterialAutoRouter(
  replaceInRouteName: 'Page,Route,Screen',
  routes: <AutoRoute>[
    AutoRoute(path: '/home', page: HomeScreen, name: 'Home'),
    AutoRoute(path: '/register', page: RegisterScreen, name: 'Register'),
    AutoRoute(path: '/login', page: LoginScreen, name: 'Login'),
    AutoRoute(path: '/initial', page: InitialScreen, name: 'Initial', initial: true),
  ],
)
// extend the generated private router
class AppRouter extends _$AppRouter {}

final appRouter = AppRouter();
