/// Generated By XFlutter Cli.
///

class Env {
  static const localhost = "http://192.168.1.8:3000";
  static const stagingUrl = "https://xdevelopment.herokuapp.com";
  static const liveUrl = "https://www.domain.com";

  static const baseUrl = stagingUrl;

  static const apiUrl = "$baseUrl/api";

  /// pagination
  static const perPage = 15;
}
