/// Generated By XFlutter Cli.
///

import 'dart:developer' as developer;
import 'package:flutter/foundation.dart';

void logger(String message, {String? name}) {
  if (kDebugMode) {
    developer.log(message, time: DateTime.now(), name: name ?? "Debug");
  }
}
