/// Generated By XFlutter Cli.
///

import 'package:flutter/material.dart';
import 'package:flutterx_live_data/flutterx_live_data.dart';
import "package:livedata_app/ui/widgets/instance/instance_state.dart";
import "./viewmodels/users_viewmodel.dart";
import 'package:livedata_app/ui/widgets/loaders/live_data_loader.dart';
import 'package:livedata_app/ui/core/responsive/screen_type_layout.dart';
import 'mobile/users_mobile_screen.dart';
import 'package:livedata_app/ui/core/layouts/base_scaffold.dart';

class UsersScreen extends StatefulWidget {
  const UsersScreen({Key? key}) : super(key: key);

  @override
  State<UsersScreen> createState() => _UsersScreenState();
}

class _UsersScreenState extends State<UsersScreen> with InstanceState<UsersScreen, UsersViewModel>, StateObserver {
  @override
  Widget screen(BuildContext context, viewModel) {
    return Stack(
      children: [
        BaseScaffold(
          builder: (context, theme) => const ScreenTypeLayout(
            mobile: UsersMobileScreen(),
          ),
        ),
        LoadingListenerWidget(loading: viewModel.baseParams.loading),
      ],
    );
  }

  @override
  UsersViewModel registerInstance() => UsersViewModel();
}
