/// Generated By XFlutter Cli.
///

import 'package:flutter/material.dart';
import 'package:livedata_app/ui/resources/colors/colors.dart';
import 'package:livedata_app/ui/screens/settings/settings_screen.dart';
import 'package:livedata_app/ui/screens/users/users_screen.dart';
import 'package:livedata_app/ui/core/layouts/theme_widget.dart';

class HomeMobileScreen extends StatelessWidget {
  const HomeMobileScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ThemeWidget(
      builder: (context, theme) {
        return DefaultTabController(
          length: 2,
          initialIndex: 0,
          child: Column(
            children: const [
              Expanded(
                /// layouts
                child: TabBarView(
                  children: [
                    UsersScreen(),
                    SettingsScreen(),
                  ],
                ),
              ),

              /// tabs
              TabBar(
                labelColor: DesignColors.primaryColor,
                unselectedLabelColor: DesignColors.secondaryColor,
                indicatorColor: DesignColors.primaryColor,
                tabs: [
                  Tab(icon: Icon(Icons.home)),
                  Tab(icon: Icon(Icons.settings)),
                ],
              ),
            ],
          ),
        );
      },
    );
  }
}
