/// Generated By XFlutter Cli.
///

import 'package:formz/formz.dart';

enum ConfirmedPasswordValidationError {
  invalid,
  mismatch,
}

class FormzConfirmPassword extends FormzInput<String, ConfirmedPasswordValidationError> {
  final String password;

  const FormzConfirmPassword.pure({this.password = ''}) : super.pure('');
  const FormzConfirmPassword.dirty({required this.password, String value = ''}) : super.dirty(value);

  @override
  ConfirmedPasswordValidationError? validator(String value) {
    if (value.isEmpty) {
      return ConfirmedPasswordValidationError.invalid;
    }
    return password == value ? null : ConfirmedPasswordValidationError.mismatch;
  }
}

extension Explanation on ConfirmedPasswordValidationError {
  String? get message {
    switch (this) {
      case ConfirmedPasswordValidationError.mismatch:
        return 'Password not confirmed';
      default:
        return null;
    }
  }
}
