/// Generated By XFlutter Cli.
///

import 'package:flutter/material.dart';
import 'package:flutter_native_splash/flutter_native_splash.dart';
import 'package:livedata_app/controllers/authentication_controller.dart';
import 'package:livedata_app/router/app_router.dart';

class InitialScreen extends StatefulWidget {
  const InitialScreen({Key? key}) : super(key: key);

  @override
  State<InitialScreen> createState() => _InitialScreenState();
}

class _InitialScreenState extends State<InitialScreen> {
  @override
  void initState() {
    WidgetsBinding.instance.addPostFrameCallback((_) {
      Future.delayed(const Duration(seconds: 1), checkAuth);
    });
    super.initState();
  }

  void checkAuth() async {
    final isLogin = await AuthenticationController.loggedIn();
    FlutterNativeSplash.remove();
    appRouter.replace(isLogin ? const Home() : const Login());
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(),
    );
  }
}
